apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-test-dpl
  labels:
    app: gradle-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradle-test
  template:
    metadata:
      labels:
        app: gradle-test
    spec:
      containers:
      - name: gradle-test-app
        image: VAR_IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 18998
        resources:
          limits:
            cpu: 100
        livenessProbe:
          httpGet:
            path: /health
            port: 18998
          initialDelaySeconds: 10
          periodSeconds: 10