apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gradle-test-hpa
  labels:
    app: gradle-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gradle-test-dpl
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40