name: Image build, push, deploy

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-push:
    name: Build image and push to GCR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      WORKFLOW_RUN_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: GCloud setup
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ vars.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker Client
      run: gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry
      run: |
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:v$WORKFLOW_RUN_NUMBER
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:v$WORKFLOW_RUN_NUMBER
