name: Image build, push, deploy

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-push:
    name: Build image and push to GCR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
      GKE_ZONE: ${{ vars.GKE_ZONE }}
      WORKFLOW_RUN_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: chmod +x gradlew

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: GCloud Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: GCloud setup
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Configure Docker Client
      run: gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.$WORKFLOW_RUN_NUMBER
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.$WORKFLOW_RUN_NUMBER

    - name: Install kubectl
      run: |-
        gcloud components install kubectl
        gcloud components install gke-gcloud-auth-plugin
    
    - name: Configure kubectl
      run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $GKE_ZONE --project $PROJECT_ID

    - name: Deploy to cluster
      run: cat $GITHUB_WORKSPACE/Deployment.yml | sed -e "s|VAR_IMAGE_NAME|gcr.io/$PROJECT_ID/$IMAGE_NAME:latest|g" | kubectl apply -f -

    - name: Create service
      run: kubectl apply -f $GITHUB_WORKSPACE/Service.yml
    
    - name: Rollout deployment
      run: kubectl rollout restart deployment

    - name: test
      run: |-
        kubectl get deployment
        kubectl get service
